ruby_on_rails/facemash/config/routes.rb
Facemash::Application.routes.draw do
  resources :faces

  get 'ranklist' => 'ranklist#index'
  get 'mash' => 'mash#index'
  post 'mash' => 'mash#update'

  

end

ruby_on_rails/facemash/app/models/face.rb
class Face < ActiveRecord::Base
	mount_uploader :image, FaceUploaderUploader

	validates_presence_of :name, :image
end

ruby_on_rails/facemash/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby_on_rails/facemash/app/controllers/faces_controller.rb
class FacesController < ApplicationController
  before_action :set_face, only: [:show, :edit, :update, :destroy]

  # GET /faces
  # GET /faces.json
  def index
    @faces = Face.all
  end

  # GET /faces/1
  # GET /faces/1.json
  def show
  end

  # GET /faces/new
  def new
    @face = Face.new
  end

  # GET /faces/1/edit
  def edit
  end

  # POST /faces
  # POST /faces.json
  def create
    @face = Face.new(face_params)

    respond_to do |format|
      if @face.save
        format.html { redirect_to @face, notice: 'Face was successfully created.' }
        format.json { render action: 'show', status: :created, location: @face }
      else
        format.html { render action: 'new' }
        format.json { render json: @face.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faces/1
  # PATCH/PUT /faces/1.json
  def update
    respond_to do |format|
      if @face.update(face_params)
        format.html { redirect_to @face, notice: 'Face was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @face.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faces/1
  # DELETE /faces/1.json
  def destroy
    @face.destroy
    respond_to do |format|
      format.html { redirect_to faces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_face
      @face = Face.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def face_params
      params.require(:face).permit(:name, :image, :elo_rating, :won, :lost)
    end
end

ruby_on_rails/facemash/app/controllers/mash_controller.rb
class MashController < ApplicationController
	def index
		@faces = Face.find(:all).sample(2)

		@face_1 = @faces[0]
		@face_2 = @faces[1]


	end

	
	def update
		@face_1 = Face.find(params[:face1])
		@face_2 = Face.find(params[:face2])

		@selection = params[:selection]
		if (@selection == @face_1.id)
			update_elo_rating(@face_1,@face_2)
		else
			update_elo_rating(@face_2,@face_1)
		end
		
		##Update rating according to the elo_rating theory

		rank_diff = 

		puts @winner
		redirect_to(:action=>"index")
	end

	def update_elo_rating(winner, looser)
		rank_diff = winner.elo_rating - looser.elo_rating
		exp = (-1 * rank_diff) / 400
		odds = 1/(1+ 10 ** exp)
		k = 32
	    if winner.elo_rating < 2100
        	k = 32
    	elsif winner.elo_rating >= 2100
        	k = 24
    	else
        	k = 16
    	end	
    
    	winner.elo_rating = winner.elo_rating + (k*(1-odds))
    	looser.elo_rating = looser.elo_rating - (k*(1-odds))
    
    	winner.won += 1
    	looser.lost += 1

    	winner.save
    	looser.save
	end
end

ruby_on_rails/facemash/app/controllers/ranklist_controller.rb
class RanklistController < ApplicationController
	def index
		@result = Face.find(:all,  :order=> 'elo_rating desc')
	end
end

ruby_on_rails/facemash/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_on_rails/facemash/app/helpers/faces_helper.rb
module FacesHelper
end

ruby_on_rails/facemash/app/helpers/mash_helper.rb
module MashHelper
end

ruby_on_rails/facemash/app/helpers/ranklist_helper.rb
module RanklistHelper
end

ruby_on_rails/facemash/app/views/faces/_form.html.erb
<%= form_for @face, html: { multipart: true }  do |f| %>
  <% if @face.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@face.errors.count, "error") %> prohibited this face from being saved:</h2>

      <ul>
      <% @face.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :elo_rating %><br>
    <%= f.text_field :elo_rating %>
  </div>
  <div class="field">
    <%= f.label :won %><br>
    <%= f.number_field :won %>
  </div>
  <div class="field">
    <%= f.label :lost %><br>
    <%= f.number_field :lost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby_on_rails/facemash/app/views/faces/edit.html.erb
<h1>Editing face</h1>

<%= render 'form' %>

<%= link_to 'Show', @face %> |
<%= link_to 'Back', faces_path %>

ruby_on_rails/facemash/app/views/faces/index.html.erb
<h1>Listing faces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Elo rating</th>
      <th>Won</th>
      <th>Lost</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @faces.each do |face| %>
      <tr>
        <td><%= face.name %></td>
        <td><%= face.image %></td>
        <td><%= face.elo_rating %></td>
        <td><%= face.won %></td>
        <td><%= face.lost %></td>
        <td><%= link_to 'Show', face %></td>
        <td><%= link_to 'Edit', edit_face_path(face) %></td>
        <td><%= link_to 'Destroy', face, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Face', new_face_path %>

ruby_on_rails/facemash/app/views/faces/new.html.erb
<h1>New face</h1>

<%= render 'form' %>

<%= link_to 'Back', faces_path %>

ruby_on_rails/facemash/app/views/faces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @face.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @face.image %>
</p>

<p>
  <strong>Elo rating:</strong>
  <%= @face.elo_rating %>
</p>

<p>
  <strong>Won:</strong>
  <%= @face.won %>
</p>

<p>
  <strong>Lost:</strong>
  <%= @face.lost %>
</p>

<%= link_to 'Edit', edit_face_path(@face) %> |
<%= link_to 'Back', faces_path %>

ruby_on_rails/facemash/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facemash</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ruby_on_rails/facemash/app/views/mash/index.html.erb
<center>
<div class="box">
<%= image_tag(@face_1.image,:width => "400px", :id=>"FACE_1", :face_id=>@face_1.id, :class=>"face") %>
<br/>
Name :: <%= @face_1.name %>
<br/>
Rating :: <%= @face_1.elo_rating %>
<br/>
Won :: <%= @face_1.won %>
<br/>
Lost :: <%= @face_1.lost %>
</div>
<div class="box">
<%= image_tag(@face_2.image,:width => "400px", :id=>"FACE_2", :face_id=>@face_2.id, :class=>"face") %>
<br/>
Name :: <%= @face_2.name %>
<br/>
Rating :: <%= @face_2.elo_rating %>
<br/>
Won :: <%= @face_2.won %>
<br/>
Lost :: <%= @face_2.lost %>
</div>
</center>


<%= form_tag do %>
<%= hidden_field_tag("face1", @face_1.id) %>
<%= hidden_field_tag("face2", @face_2.id) %>
<%= hidden_field_tag("selection") %>
<% end %>

<script type='text/javascript'>
$(document).ready(function(){
	$(".face").click(function(){
		$("#selection").value=$(this).attr("face_id");
		$("form").submit();
	});
});
</script>
<style type='text/css'>
	.face{
		padding-left : 100px;
	}
	.box {
		float : left;
	}
</style>

ruby_on_rails/facemash/app/views/ranklist/index.html.erb
<h1>Ranklist</h1>
<% count = 1 %>
<table>
  <thead>
    <tr>
      <th>Rank </th>
      <th>Name</th>
      <th>Image</th>
      <th>Elo rating</th>
      <th>Won</th>
      <th>Lost</th>
    </tr>
  </thead>

  <tbody>
    <% @result.each do |face| %>
      <tr>
      	<td> <%= count %> <% count+=1 %>
        <td><%= face.name %></td>
        <td><%= image_tag(face.image, :width => "400px") %></td>
        <td><%= face.elo_rating %></td>
        <td><%= face.won %></td>
        <td><%= face.lost %></td>
      </tr>
    <% end %>
  </tbody>
</table>